import { Inter } from 'next/font/google'
import '../styles/globals.css';
import '../styles/hot-fixes.css'
import '../styles/index.css'
import '../styles/app.css'
import '../styles/custom.css'
import Provider from '@components/common/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
